describe('anonymous calendar;', () => {
  it('it can set current month', () => {
    cy.visit('/')
      .get('#cal-mth')
      .select('Mar')
      .get('#cal-yr')
      .select('2020')
      .get('#cal-set')
      .click()
      .get('#calendar > :nth-child(14)')
      .should('have.text', '1')
      .get(':nth-child(44)')
      .should('have.text', '31')
  })
  it('it can add task', () => {
    cy.get('#calendar > :nth-child(19)')
      .click()
      .get('[data-testid=date]')
      .should('have.text', '6 Mar 2020')
      .get('#evt-details')
      .type('new event')
      .get('.blue')
      .click()
      .get('.evt-item')
      .should('have.text', 'new event')
  })
})
